### ISSUE TITLE
BinWrite attribute codegen checklist

### ISSUE THREAD

**Issue by jam1garner** [jam1garner/binrw#41]
* [x] Top-level attributes
  * [x] Struct
    * [x] big
    * [x] little
    * [x] is_big
    * [x] is_little
    * [x] map
    * [x] magic
    * [x] imports
    * [x] assert
  * [x] Enum
    * [x] big
    * [x] little
    * [x] is_big
    * [x] is_little
    * [x] map
    * [x] magic
    * [x] imports
  * [x] UnitOnlyEnum
    * [x] big
    * [x] little
    * [x] is_big
    * [x] is_little
    * [x] map
    * [x] magic
    * [x] imports
    * [x] repr
* [x] Field-level attributes
  * [x] big
  * [x] little
  * [x] is_big
  * [x] is_little
  * [x] map
  * [x] magic
  * [x] args
  * [x] calc
  * [x] ignore
  * [x] write_with
  * ~~count~~
  * [x] restore_position
  * [x] assert
  * [x] pad_before
  * [x] pad_after
  * [x] align_before
  * [x] align_after
  * [x] seek_before
  * [x] pad_size_to

**Comment by dmgolembiowski** [comment]
Looking at:

> * [ ]  Top-level attributes
> 
> * [ ]  Struct
> ...
> * [ ]  map
> ...
> * [ ]  Enum
> ...
> * [ ]  map
> ...
> * [ ]  UnitOnlyEnum
> ...
> * [ ]  map
> ...
> * [ ]  Field-level attributes
> 
> * [x]  big
> * [x]  little
> * [x]  is_big
> * [x]  is_little
> * [x]  map
> * [x]  magic
> * [x]  args
> * [x]  calc
> * [x]  ignore
> * [x]  write_with
> * [ ]  count
> * [ ]  restore_position
> * [ ]  temp
> * [ ]  assert
> * [x]  pad_before
> * [x]  pad_after
> * [x]  align_before
> * [x]  align_after
> * [x]  seek_before
> * [x]  pad_size_to

How do you feel about driving `.map(|slice| ...)` out into its own separate trait, `binmap`?
